name: Semantic Release
on: push
jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 13.5
    - name: Install dependencies
      run: yarn install
    - name: Test
      run: yarn test:prod
    - name: Build
      run: yarn build
    - name: Release to NPM
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate docs
      run: yarn docs
    - name: Version docs
      uses: bobrown101/version-docs@v2.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        doc-location: docs
        doc-branch: gh-pages
    - name: Deploy docs
      uses: bobrown101/deploy-branch@v2.0.0
      with:
        provider: NETLIFY
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: 3e5f813a-792c-4937-8e96-dc1ad570ce80
        branch: gh-pages
        github-token: ${{ secrets.GITHUB_TOKEN }}
